name: "Cloud Agent CI/CD"

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for Checkout

jobs:
  terraform-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend-config="prod.config"

      # In enterprise, we use -var-file to target specific environments
      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -var-file="envs/prod.tfvars" -auto-approve

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        working-directory: ./
        run: |
          pip install -r ./src/requirements.txt

      - name: Run Connection Test
        working-directory: ./
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: python ./src/app.py